name: SquidHQ
main: com.squidhq.plugin.Plugin
version: 1
commands:
  sqcheck:
    description: Check whether a given player is running SquidHQ
    usage: /sqcheck <player>
    permission: squidhq.check
  sqstats:
    description: Check the current online player stats
    usage: /sqstats
    permission: squidhq.stats

permissions:
  squidhq.stats:
    default: op
    description: Allows use of /sqstats
  squidhq.check:
    default: op
    description: Allows use of /sqcheck